### ISSUE TITLE
Installing with gtsam-4.1.0

### ISSUE THREAD

**Issue by dishank-b** [best-of-acrv/gtsam-quadrics#7]
I have already gtsam-4.1.0 installed on my computer with python binding? 

How should I proceed to install gtsam_quadrics?

**Comment by btalb** [comment]
See discussion on #6 .

**Comment by btalb** [comment]
Closing. We've moved to GTSAM 4.1.1 with [release v0.1.1](https://github.com/best-of-acrv/gtsam-quadrics/releases/tag/v0.1.1).
